# Generated by Django 2.2.6 on 2019-12-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gabinete', models.CharField(max_length=100)),
                ('Fuente', models.CharField(max_length=100)),
                ('PlacaMadre', models.CharField(max_length=100)),
                ('Ram', models.CharField(max_length=100)),
                ('Procesador', models.CharField(max_length=100)),
                ('TarjetaVideo', models.CharField(max_length=100)),
                ('Almacenamiento', models.CharField(max_length=100)),
            ],
        ),
    ]
